### ISSUE TITLE
Fail to build on Antergos

### ISSUE THREAD

**Issue by deepankarsharma** [snuf/iomemory-vsl#35]
For some reason the elevator_* functions are throwing up an implicitly declared error. Any pointers for a fix?

FIO_DRIVER_NAME=iomemory-vsl \
FIO_SCSI_DEVICE=0 \
FUSION_DRIVER_DIR=/usr/src/iomemory-vsl-3.2.15 \
SUBDIRS=/usr/src/iomemory-vsl-3.2.15 \
EXTRA_CFLAGS+="-I/usr/src/iomemory-vsl-3.2.15/include -DBUILDING_MODULE -DLINUX_IO_SCHED" \
INSTALL_MOD_DIR=extra/fio \
INSTALL_MOD_PATH= \
KFIO_LIB=kfio/x86_64_cc82_libkfio.o_shipped \
modules
make[1]: Entering directory '/usr/lib/modules/4.18.8-arch1-1-ARCH/build'
  CC [M]  /usr/src/iomemory-vsl-3.2.15/kblock.o
/usr/src/iomemory-vsl-3.2.15/kblock.c: In function ‘kfio_elevator_change’:
/usr/src/iomemory-vsl-3.2.15/kblock.c:2238:5: error: implicit declaration of function ‘elevator_exit’; did you mean ‘elevator_alloc’? [-Werror=implicit-function-declaration]
     elevator_exit(q->elevator);
     ^~~~~~~~~~~~~
     elevator_alloc
/usr/src/iomemory-vsl-3.2.15/kblock.c:2243:9: error: implicit declaration of function ‘elevator_init’; did you mean ‘elevator_alloc’? [-Werror=implicit-function-declaration]
     if (elevator_init(q, name))
         ^~~~~~~~~~~~~
         elevator_alloc

**Comment by plappermaul** [comment]
Elevator functions have been moved around in 4.18. Try to include blk.h (additionally to elevator.h).

Markus

Am 19.09.2018 01:24 schrieb Deepankar Sharma <notifications@github.com>:

For some reason the elevator_* functions are throwing up an implicitly declared error. Any pointers for a fix?

FIO_DRIVER_NAME=iomemory-vsl
FIO_SCSI_DEVICE=0
FUSION_DRIVER_DIR=/usr/src/iomemory-vsl-3.2.15
SUBDIRS=/usr/src/iomemory-vsl-3.2.15
EXTRA_CFLAGS+="-I/usr/src/iomemory-vsl-3.2.15/include -DBUILDING_MODULE -DLINUX_IO_SCHED"
INSTALL_MOD_DIR=extra/fio
INSTALL_MOD_PATH=
KFIO_LIB=kfio/x86_64_cc82_libkfio.o_shipped
modules
make[1]: Entering directory '/usr/lib/modules/4.18.8-arch1-1-ARCH/build'
CC [M] /usr/src/iomemory-vsl-3.2.15/kblock.o
/usr/src/iomemory-vsl-3.2.15/kblock.c: In function ‘kfio_elevator_change’:
/usr/src/iomemory-vsl-3.2.15/kblock.c:2238:5: error: implicit declaration of function ‘elevator_exit’; did you mean ‘elevator_alloc’? [-Werror=implicit-function-declaration]
elevator_exit(q->elevator);
^~~~~~~~~~~~~
elevator_alloc
/usr/src/iomemory-vsl-3.2.15/kblock.c:2243:9: error: implicit declaration of function ‘elevator_init’; did you mean ‘elevator_alloc’? [-Werror=implicit-function-declaration]
if (elevator_init(q, name))
^~~~~~~~~~~~~
elevator_alloc

**Comment by deepankarsharma** [comment]
blk.h is under block/blk.h in linux-4.18.8 and is not available under include/linux hence build of the module cannot locate it.

**Comment by deepankarsharma** [comment]
Found the commit in question and will try to reverse it locally to see if I can make some progress -> https://www.systutorials.com/linux-kernels/658144/block-unexport-elevator_init-exit-linux-4-18/

**Comment by deepankarsharma** [comment]
I was able to get the driver built but for some reason it did not recognize my card. I have since installed debian and am using the official driver. Just updating this bug for completeness.
