### ISSUE TITLE
Kernel 5.5 changes file_operations to proc_ops

### ISSUE THREAD

**Issue by MariusSchiffer** [snuf/iomemory-vsl#59]
Compilation fails on 5.6. Replacing file_operations with proc_ops in kfile.c works.
I can create a PR later for this and #58 later.

**Comment by snuf** [comment]
As in #58 the fix is already https://github.com/snuf/iomemory-vsl4 code-cleanup haven't had the time to backport yet, will make a fix now.

Best

**Comment by snuf** [comment]
@MariusSchiffer fix is merged to next_generation in #60, tests ran clean.
